#!/usr/bin/env bash
# Setup haproxy on server lb-01 to serve web-01 and web-02.
sudo apt-get -y update
sudo apt-get -y install haproxy

echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server 6517-web-01 54.152.116.247 check
        server 6517-web-02 34.207.126.103 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart